In [1]:
import numpy as np

# One dimensional array

In [2]:
a = [1,2,3,4,5] 
b = np.array(a) 
b

array([1, 2, 3, 4, 5])

In [3]:
a = [] 
size  = int(input("Enter size:")) 
for i in range(size):
    val = int(input("Enter number:")) 
    a.append(val) 
    
print(a) 
b = np.array(a) 
b

Enter size:5
Enter number:1
Enter number:2
Enter number:3
Enter number:4
Enter number:5
[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

# Two dimensional array

In [4]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]] 
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# How to check size and diemnsion of an array  ?

In [5]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]] 
b = np.array(a) 
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print("Total Dimensions :" , b.ndim) 
print("Shape of an array :" , b.shape) 

Total Dimensions : 2
Shape of an array : (3, 3)


# Numpy Functions ==> 



# 1 . Zeros ==> This function create an array (either one dimensional or multi dimensional) and fill all the values with zeros . 

In [7]:
import numpy as np 
a = np.zeros(5) 
a

array([0., 0., 0., 0., 0.])

In [8]:
b = np.zeros((2,3)) 
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
b.ndim

2

In [10]:
a.ndim

1

# 2 . Ones ==> This function creats an array (either one dimensional or multi dimensional) and fill all the values with one . 

In [11]:
import  numpy as np 
a = np.ones(5) 
a

array([1., 1., 1., 1., 1.])

In [12]:
b = np.ones((2,3)) 
b

array([[1., 1., 1.],
       [1., 1., 1.]])

# 3 . eye ==> This function creats an array with all the digonal elements as 1 and rest are 0(In square matrix). In non-square matrix the value are sstill one for digonal (upto which it can draw digonal ) and rest are zero . 

In [13]:
import numpy as np 
a = np.eye(3) 
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
b = np.eye(3,4) 
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 4 . diag ==> This function creats a two dimensional array with all the digonal elements as the given value and rest are zero . 

In [15]:
import numpy as np
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# 5 . randint ==> This  function is used to generate a random number between a given range . 

# syntax == randint(min_value , max_value , total_numbers) 

In [18]:
import numpy as np 
a = np.random.randint(1,10,3) 
a

array([6, 9, 4])

# 6 . rand() ==> This function is used to generate a random number between 0 to 1 . 

# syntax == rand(numberof values) 

In [19]:
import numpy as np 

a = np.random.rand(5) 
a

array([0.06708846, 0.07141926, 0.24761339, 0.64343346, 0.98412292])

# 7 . randn() ==> This function is used to generate a random number from -3 to close 3 . This may return positive or negative numbers as well . 

# syntax == random.randn(number of values) 

In [20]:
import numpy as np 
a = np.random.randn(5) 
a

array([-0.83676406, -0.64319371,  1.93291174,  0.85973616, -0.26271558])

# Reshaping Data

In [21]:
import numpy as np 

a = np.random.randint(1,50,12) 

a

array([36, 23, 31, 30,  9, 29, 41, 13, 11, 23, 13, 45])

In [22]:
a.shape 

(12,)

In [23]:
a = a.reshape(2,6) 
a

array([[36, 23, 31, 30,  9, 29],
       [41, 13, 11, 23, 13, 45]])

In [25]:
a = a.reshape(6,2) 
a

array([[36, 23],
       [31, 30],
       [ 9, 29],
       [41, 13],
       [11, 23],
       [13, 45]])

In [26]:
a = a.reshape(3,4) 
a

array([[36, 23, 31, 30],
       [ 9, 29, 41, 13],
       [11, 23, 13, 45]])

In [28]:
a = a.reshape(4,3) 
a

array([[36, 23, 31],
       [30,  9, 29],
       [41, 13, 11],
       [23, 13, 45]])

In [30]:
a = a.reshape(12,1) 
a

array([[36],
       [23],
       [31],
       [30],
       [ 9],
       [29],
       [41],
       [13],
       [11],
       [23],
       [13],
       [45]])

# principal of -1 

In [33]:
a = a.reshape(-1 , 4) 
a

array([[36, 23, 31, 30],
       [ 9, 29, 41, 13],
       [11, 23, 13, 45]])

# Seed Function ()  ==> We know that randint function generates random numbers . Everytime we run the program  , new set of random number is generated . So , solve this problem we will use seed function . 

In [36]:
import numpy as np 

np.random.seed(12) 
a = np.random.randint(1,100 , 10) 
a

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

#### np.random.seed(111) 
a = np.random.randint(1,500,30).reshape(6,5) 
a

# View Vs Copy ==> When we slice a sub-array from an array , it may be done by two ways . 

In [39]:
import numpy as np 
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6] 
b[:] = 0 
a

array([10, 20, 30,  0,  0,  0, 70, 80])

# copy 

In [40]:
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6].copy() 
b[:] = 0 
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [41]:
b

array([0, 0, 0])

# conditional selection 

In [42]:
import numpy as np 
a = np.arange(1,16) 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [44]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [46]:
b = a>10 
a[b]

array([11, 12, 13, 14, 15])

In [47]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

# Operations on Array 

In [52]:
import numpy as np 
a = np.arange(1,5) 
a*2

array([2, 4, 6, 8])

In [49]:
a+2 

array([3, 4, 5, 6])

In [50]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [60]:
a  = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [61]:
b = np.array([5,6,7,8]).reshape(2,2) 
b

array([[5, 6],
       [7, 8]])

In [55]:
a+b 

array([[ 6,  8],
       [10, 12]])

In [56]:
b-a

array([[4, 4],
       [4, 4]])

In [57]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [58]:
a*b

array([[ 5, 12],
       [21, 32]])

In [59]:
a.dot(b) 

array([[19, 22],
       [43, 50]])

# some more important numpy functions 

In [62]:
import  numpy as np 
a = np.array([10,20,30,40,50]) 
np.min(a) 

10

In [63]:
np.max(a) 

50

In [64]:
np.argmin(a) 

0

In [65]:
np.argmax(a) 

4

In [66]:
np.sqrt(a) 

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [67]:
np.sin(a) 

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

# Linspace() ==> This function returns value between a given range and with a same gap between consicutive elements . 

In [68]:
import numpy as np 

a = np.linspace(1,2,5) 
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [69]:
import numpy as np 

np.random.seed(122) 
a = np.random.randint(1,21,9).reshape(3,3) 
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [70]:
np.sum(a) 

116

In [71]:
np.sum(a , axis = 1) 

array([40, 46, 30])

In [72]:
np.min(a) 

3

In [73]:
np.max(a) 

17

In [74]:
np.cumsum(a) 

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

In [75]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

# np.unique(arr , return_index = True , return_counts = True) 

returns 3 array . 
1 . the array with unique values . 
2 . the array with respective index value . 
3 . the array with counting of frequencey . 

In [78]:
a = np.array([10,20,30,40,10,20,50]) 
np.unique(a , return_index  = True , return_counts = True) 


(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [79]:
a = np.array([1,2,3,4]) 
b = np.array([5,6,7,8]) 
a

array([1, 2, 3, 4])

In [80]:
b

array([5, 6, 7, 8])

In [81]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])